### ISSUE TITLE
Use Json or Yaml File?

### ISSUE THREAD

**Issue by Latrasis** [Latrasis/petrovich-rs#1]
We need to decide which format to pick: either `json` from `petrovich-js` or `yaml` from `petrovich-ruby`.

**Comment by road21** [comment]
I think it doesn't matter. Just pick smth. I prefer yaml.

**Comment by Latrasis** [comment]
Yaml it is then.

**Comment by Latrasis** [comment]
EDIT: petrovich-ruby doesn't have a yaml file, it has `.tsv` file. So I guess i'll switch to `json` instead.
