### ISSUE TITLE
Gender Constructor?

### ISSUE THREAD

**Issue by Latrasis** [Latrasis/petrovich-rs#5]
For inflection, we currently take all 3 parameters: `Gender`, `name`, `Case`. The ruby version however has a `Gender` constructor included instead. I'm guessing `Petrovich::new` should take a `Gender` then, and then have a `Default` that doesn't take any parameters. (Just guesses the gender).

**Comment by Latrasis** [comment]
Thinking about it a little more, should we have it simply as methods instead?

So this:
```rust
let sample = Petrovich::new(Gender::male);
```

Or this?
```rust
let sample = Petrovich::male(); 
```

**Comment by road21** [comment]
To be honest, I don't understand why Ruby version's constructor takes Gender argument. I would like to use one Petrovich object for inflecting male and female names. So, I offer to stay on our version, but implement methods like ```petrovich.firstname("Лёша", Case::Genitive)``` with guessing gender.

**Comment by Latrasis** [comment]
Unfortunately rust doesn't have overload-able operators, so we would have to have 6 methods. (3 names by 2 Guessing and Non-Guessing?)
